Q1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

Ans. NumPy is the cornerstone of scientific computing in Python. Here's a breakdown of its purpose, advantages, and how it enhances Python's numerical capabilities:

-> Purpose:

 Efficient Array Operations: NumPy's primary goal is to provide efficient support for large, multi-dimensional arrays and matrices.

-> Advantages:

 * Speed and Efficiency:-

Vectorization: NumPy allows you to perform operations on entire arrays at once, rather than looping through individual elements. This leverages optimized C/C++ code under the hood, resulting in significant speed improvements.

Memory Efficiency: NumPy arrays are more memory-efficient than Python lists, especially for large datasets.

* Broad Functionality:-

Offers a vast collection of high-level mathematical functions for linear algebra, Fourier transforms, random number generation, and more.

Foundation for Other Libraries: NumPy serves as the foundation for many other scientific Python libraries, such as SciPy, pandas, and scikit-learn.

How it enhances Python:

Efficient Data Structures: Introduces the ndarray object, a powerful data structure optimized for numerical computations.

Linear Algebra Support: Provides efficient implementations of linear algebra operations like matrix multiplication, eigenvalues, and singular value decomposition.

Broadcasting: Enables operations between arrays of different shapes, simplifying complex calculations.

In summary:

NumPy bridges the gap between Python's high-level syntax and the performance of low-level languages for numerical computing. Its efficient array operations, extensive mathematical functions, and integration with other scientific libraries make it an indispensable tool for data scientists, researchers, and engineers.

Q2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

Ans. * np.mean():

Calculates the arithmetic mean of an array.
Simple and efficient for calculating the average of a set of values where all values have equal weight.

* np.average():

More versatile.

Calculates the weighted average by default if weights are provided.
Can also be used to calculate the arithmetic mean (if no weights are provided).

When to Use:>

np.mean(): Ideal for most common use cases where all values have equal weight.

np.average():
Use when you need to calculate a weighted average.
Example: Calculating the average grade in a class where some assignments have more weight than others.
Example: Determining the average stock price based on trading volume (volume as weights).

In Summary:

np.mean() is suitable for standard averaging needs.
np.average() offers more flexibility, especially when dealing with weighted data.

Q3. Describe the methods of for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

Ans. Reversing NumPy Arrays:>

* np.flip(a, axis=None):

* This is the primary method for reversing arrays along specified axes.

* axis:
If None (default), reverses the order of elements in all dimensions of the array.

If an integer, reverses the order of elements along the specified axis.
Examples:

1D Array:

In [ ]:
import numpy as np

arr1d = np.array([1, 2, 3, 4, 5])
reversed_arr1d = np.flip(arr1d)
print(reversed_arr1d)  # Output: [5 4 3 2 1]

In [ ]:
1D Array:>

arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])

# Reverse along the first axis (rows)
reversed_rows = np.flip(arr2d, axis=0)
print(reversed_rows)
# Output:
# [[4 5 6]
#  [1 2 3]]

# Reverse along the second axis (columns)
reversed_cols = np.flip(arr2d, axis=1)
print(reversed_cols)
# Output:
# [[3 2 1]
#  [6 5 4]]

# Reverse along all axes
reversed_all = np.flip(arr2d)
print(reversed_all)
# Output:
# [[6 5 4]
#  [3 2 1]]

Q4. How can you determine the data types of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

Ans. Determining Data Types in NumPy Arrays:

dtype attribute: The most direct way to determine the data type of elements in a NumPy array is using the dtype attribute.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3.0])
print(arr.dtype)  # Output: float64

Importance of Data Types in Memory Management and Performance:

Memory Efficiency:

* Data types directly influence the amount of memory used to store the array.

* Using smaller data types (e.g., int32 instead of int64) when possible can significantly reduce memory consumption, especially for large arrays.

Performance:

* NumPy operations are optimized for specific data types.

* Using the correct data type can lead to significant performance improvements in calculations and memory access.

For example, operations on arrays of integers are generally faster than operations on arrays of floating-point numbers.

In summary:

Understanding and choosing the appropriate data type for your NumPy arrays is crucial for efficient memory usage and optimal performance in your numerical computations. By carefully selecting data types, you can minimize memory consumption and maximize the speed of your NumPy operations.

Q5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

Ans. ndarrays in NumPy

-> Definition:

* ndarray (N-dimensional array) is the fundamental data structure in NumPy.

* It represents a multi-dimensional, homogeneous array of elements (usually numbers).

* Homogeneous means all elements must have the same data type (e.g., integers, floats).

-> Key Features:

* Speed and Efficiency:

*Implemented in C, making them significantly faster than Python lists for numerical operations.

*Vectorized operations allow you to perform operations on entire arrays at once, leading to significant performance gains.

* Memory Efficiency:

*More memory-efficient than Python lists, especially for large datasets.

* Multidimensional Support:

*Can represent arrays of any dimension (1D, 2D, 3D, etc.).

* Data Type Homogeneity:

All elements in an array must have the same data type, which allows for optimized memory allocation and faster computations.


Q6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Ans. NumPy arrays offer significant performance benefits over Python lists for large-scale numerical operations due to these key factors:

* Vectorization: NumPy allows you to perform operations on entire arrays at once instead of looping through individual elements. This leverages optimized C/C++ code under the hood, resulting in much faster execution.

* Memory Efficiency: NumPy arrays are more memory-efficient than Python lists, especially for large datasets. This is because:

* Homogeneous Data Type: All elements in a NumPy array must have the same data type, allowing for more efficient memory allocation and data storage. Python lists, on the other hand, can store elements of different data types, which requires more overhead.

* Contiguous Memory Allocation: NumPy arrays store data in contiguous blocks of memory, enabling faster access and improved cache utilization.

* Optimized for Numerical Operations: NumPy is specifically designed for efficient numerical computations. It provides optimized implementations for a wide range of mathematical functions, including linear algebra operations, statistical functions, and more.

In essence:

NumPy's optimized data structures, vectorized operations, and efficient memory management make it significantly faster than Python lists for most numerical computations. This performance advantage is crucial for handling large datasets and performing complex calculations efficiently in scientific computing and data analysis.

Q7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

Ans. np.vstack():

*Vertical Stacking: Stacks arrays row-wise.

*Requires the number of columns to be the same in all input arrays.

Example:

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

stacked_array = np.vstack((a, b))
print(stacked_array)
# Output:
# array([[1, 2, 3],
#        [4, 5, 6]])

* np.hstack():

*Horizontal Stacking: Stacks arrays column-wise.

*Requires the number of rows to be the same in all input arrays.

Example:>

In [ ]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

stacked_array = np.hstack((a, b))
print(stacked_array)
# Output:
# array([[1, 4],
#        [2, 5],
#        [3, 6]])

In Summary:

* np.vstack() joins arrays vertically, adding rows.

* np.hstack() joins arrays horizontally, adding columns.

Choose vstack() when you want to add rows to an existing array, and hstack() when you want to add columns.

Q8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

Ans.np.fliplr():

*Flips the array horizontally.

*In 2D arrays, it reverses the order of elements along the columns.

* np.flipud():

*Flips the array vertically.

*In 2D arrays, it reverses the order of elements along the rows.

-> Key Differences:

* Axis of Reversal:

*fliplr() reverses along the horizontal axis (columns).

*flipud() reverses along the vertical axis (rows).

* Effects on Different Array Dimensions:

*1D Array:

* fliplr() and flipud() have the same effect as np.flip() on a 1D array: they reverse the order of elements.

*2D Array:

* fliplr() reverses the order of elements within each row.

* flipud() reverses the order of rows in the array.

* Higher Dimensions:

Both functions can be used with higher-dimensional arrays, but their effects become more complex depending on the specified axis.

In Summary:

* fliplr() and flipud() are specialized functions for flipping arrays along specific axes.

* fliplr() is for horizontal flipping, and flipud() is for vertical flipping.

* For more general array flipping along any axis, use np.flip(a, axis=...).

Q9. Discuss the functionality of the array_spilt() methods in NumPy. How does it handle uneven spilts?

Ans. The np.array_split() function in NumPy is used to split an array into multiple sub-arrays.
-> Key Functionality:

* Flexibility in Splitting: Unlike np.split(), np.array_split() allows for uneven splitting of the array. This is particularly useful when the array cannot be evenly divided into the desired number of sub-arrays.

* Handling Uneven Splits:
If the array cannot be evenly divided by the specified number of splits, np.array_split() distributes the extra elements among the sub-arrays, ensuring that the resulting sub-arrays have approximately equal sizes.

Example:

In [ ]:
import numpy as np

arr = np.arange(10)  # Array from 0 to 9

# Split into 3 sub-arrays (uneven split)
sub_arrays = np.array_split(arr, 3)

print(sub_arrays)
# Output:
# [array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In this example, the array is split into 3 sub-arrays. Since 10 is not evenly divisible by 3, the first two sub-arrays have 4 elements each, and the last sub-array has 2 elements.

In summary:

np.array_split() provides a flexible way to split arrays into multiple sub-arrays, effectively handling situations where even division is not possible. This is valuable for various data processing tasks, such as dividing large datasets into smaller chunks for parallel processing or for cross-validation in machine learning.

Q10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

Ans.-> Vectorization:

* Concept: Performing operations on entire arrays at once, rather than iterating over individual elements using Python loops.

* Benefits:

*Leverages optimized C/C++ code under the hood for significantly faster execution.

*Eliminates the overhead of Python's loop interpretation, resulting in substantial performance gains.

* Broadcasting:

*Concept: A powerful mechanism that allows NumPy to perform operations on arrays with different shapes.

*Rules: NumPy attempts to automatically "broadcast" the shape of smaller arrays to match the shape of the larger array before performing the operation. This is possible under certain conditions (e.g., one array has dimensions of size 1).

* How they contribute to efficiency:

*Vectorization: By eliminating the need for explicit loops, vectorization leverages the power of NumPy's optimized C/C++ implementations, leading to dramatic speed improvements for numerical computations.

*Broadcasting: Enables efficient operations on arrays of different shapes without the need to manually reshape or duplicate data. This reduces memory usage and simplifies code.

Example:

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])  # 1D array
arr2 = 5  # Scalar (treated as an array with shape (,))

result = arr1 + arr2  # Broadcasting: scalar 5 is added to each element of arr1

print(result)  # Output: [6 7 8]

In this example, the scalar value 5 is "broadcast" across the entire array arr1, resulting in element-wise addition without the need for explicit looping.

Both vectorization and broadcasting are key concepts that contribute significantly to the efficiency and ease of use of NumPy for numerical computations.

Q11. Create a 3x3 NumPy array with random integers between 1 and 100 . Then, interchange its rows and columns.

Ans. np.vstack(): Stacks arrays vertically, adding rows. Requires the number of columns to be the same in all input arrays.

np.hstack(): Stacks arrays horizontally, adding columns. Requires the number of rows to be the same in all input arrays.

Examples:

In [ ]:
import numpy as np

a = np.array([1, 2, 3])  # 1D array
b = np.array([4, 5, 6])

# Vertical stacking
stacked_vertical = np.vstack((a, b))
print(stacked_vertical)
# Output:
# [[1 2 3]
#  [4 5 6]]

a = np.array([[1], [2], [3]])  # 2D array (column vector)
b = np.array([[4], [5], [6]])

# Horizontal stacking
stacked_horizontal = np.hstack((a, b))
print(stacked_horizontal)
# Output:
# [[1 4]
#  [2 5]
#  [3 6]]

These functions are essential for building larger arrays from smaller ones in various data manipulation tasks.

Q12. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [ ]:
Ans. import numpy as np

# Generate a 1D array with 10 random integers
arr = np.random.randint(1, 101, 10)
print("Original 1D array:", arr)

# Reshape to 2x5 array
arr_2x5 = arr.reshape(2, 5)
print("Reshaped to 2x5:", arr_2x5)

# Reshape to 5x2 array
arr_5x2 = arr.reshape(5, 2)
print("Reshaped to 5x2:", arr_5x2)

This code snippet:

1. Generates a 1D array: np.random.randint(1, 101, 10) creates an array with 10 random integers between 1 and 100 (inclusive).

2. Reshapes to 2x5: arr.reshape(2, 5) reshapes the 1D array into a 2D array with 2 rows and 5 columns.

3. Reshapes to 5x2: arr.reshape(5, 2) reshapes the 1D array into a 2D array with 5 rows and 2 columns.

This demonstrates how to easily reshape a NumPy array using the reshape() method, which is a powerful tool for manipulating array dimensions.

Q13. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting into 6x6 array.

In [ ]:
Ans. import numpy as np

# Create a 4x4 array with random float values
arr = np.random.rand(4, 4)

# Create a 6x6 array filled with zeros
padded_arr = np.zeros((6, 6))

# Place the original array within the padded array
padded_arr[1:5, 1:5] = arr

print("Original Array:\n", arr)
print("\nArray with Zero Border:\n", padded_arr)

This code does the following:

1. Creates a 4x4 array:

* np.random.rand(4, 4) creates a 4x4 NumPy array filled with random floating-point values between 0 and 1.

2. Creates a 6x6 array of zeros:

* np.zeros((6, 6)) creates a 6x6 array filled with zeros.

3. Places the original array within the padded array:

* padded_arr[1:5, 1:5] = arr
* This line places the original 4x4 array (arr) within the center of the 6x6 array (padded_arr).
* The slicing [1:5, 1:5] selects the inner 4x4 portion of the 6x6 array.

This effectively adds a single row and column of zeros around the original array, resulting in a 6x6 array with the original values embedded within it.

Q14. Using a NumPy, create an array of integers from 10 to 60 with a step of .

In [ ]:
Ans. import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
my_array = np.arange(10, 61, 5)

print(my_array)
This code will output:

[10 15 20 25 30 35 40 45 50 55 60]

* np.arange(start, stop, step): This is the core function used to create arrays of evenly spaced values.
* start: The starting value of the sequence (inclusive).
* stop: The end value of the sequence (exclusive).
* step: The difference between consecutive values in the sequence.

This concise example demonstrates how to use np.arange() to efficiently create an array of integers with a specific step size.

Q15. Create a NumPy array of strings ['python','numpy','pandas']. Apply different case transfomations (uppercase,lowercase,title case,etc.) to each element.

In [ ]:
Ans. import numpy as np

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply case transformations
lowercase_arr = arr.astype(str).lower()  # Convert to lowercase
uppercase_arr = arr.astype(str).upper()  # Convert to uppercase
title_case_arr = arr.astype(str).title()  # Convert to title case

print("Original Array:", arr)
print("Lowercase:", lowercase_arr)
print("Uppercase:", uppercase_arr)
print("Title Case:", title_case_arr)

Explanation:

1. Create the array: We create a NumPy array arr containing the strings 'python', 'numpy', and 'pandas'.
2. Case transformations:
* arr.astype(str).lower(): Converts all characters in each string to lowercase.
* arr.astype(str).upper(): Converts all characters in each string to uppercase.
* arr.astype(str).title(): Capitalizes the first character of each word in each string.

This demonstrates how to easily apply various case transformations to a NumPy array of strings using built-in functions.

Q16. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [ ]:
Ans. import numpy as np

words = np.array(["hello", "world", "numpy"])

# Insert a space between each character
spaced_words = np.char.join(" ", words)

print(spaced_words)
# Output: ['h e l l o' 'w o r l d' 'n u m p y']

Explanation:

1. Create the array: We create a NumPy array words containing the strings 'hello', 'world', and 'numpy'.
2. Insert spaces:
* np.char.join(" ", words) uses the np.char.join() function to insert a space between each character of each string in the array.

This demonstrates a concise way to modify strings within a NumPy array using the np.char module.

Q17. Create two 2D NumPy arrays and perform element-wise addition,substraction,multiplication, and division.


In [ ]:
Ans. import numpy as np

# Create two 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Element-wise addition
add_result = arr1 + arr2
print("Addition:\n", add_result)

# Element-wise subtraction
sub_result = arr1 - arr2
print("Subtraction:\n", sub_result)

# Element-wise multiplication
mul_result = arr1 * arr2
print("Multiplication:\n", mul_result)

# Element-wise division
div_result = arr1 / arr2
print("Division:\n", div_result)
Output:

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[ 5 12]
 [21 32]]
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]

Explanation:

* NumPy arrays support element-wise operations directly.
* The code creates two 2D arrays (arr1 and arr2).
* Then, it performs element-wise addition, subtraction, multiplication, and division on these arrays.
* The results are new arrays where each element is the result of the corresponding operation on the elements of the input arrays.

This demonstrates the ease of performing basic arithmetic operations on NumPy arrays.

Q18. Use NumPy to create 5x5 identity metrix, then extract its diagonal elements.

In [ ]:
Ans. import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract diagonal elements using diagonal()
diagonal_elements = np.diag(identity_matrix)

print("Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)

Explanation:

1. Create Identity Matrix:
* np.eye(5) creates a 5x5 identity matrix, which is a square matrix with 1's on the main diagonal and 0's elsewhere.
2. Extract Diagonal Elements:
*np.diag(identity_matrix) extracts the diagonal elements of the matrix and returns them as a 1D array.

This demonstrates how to easily create an identity matrix and extract its diagonal elements using NumPy functions.

Q19. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.


In [ ]:
Ans. import numpy as np

def is_prime(n):
  """Checks if a number is prime."""
  if n <= 1:
    return False
  for i in range(2, int(n**0.5) + 1):
    if n % i == 0:
      return False
  return True

# Generate a NumPy array of 100 random integers
arr = np.random.randint(0, 1000, 100)

# Find prime numbers in the array
prime_numbers = arr[list(filter(is_prime, arr))]

print("Prime numbers in the array:", prime_numbers)

Explanation:

1. Generate random array:
* np.random.randint(0, 1000, 100) creates an array of 100 random integers between 0 and 1000 (inclusive).
2. Define a prime number checking function:
* The is_prime() function checks if a given number is prime.
3. Find prime numbers:

* list(filter(is_prime, arr)) creates a list of indices where the corresponding element in the array is prime.
* arr[list(filter(is_prime, arr))] uses this list of indices to extract the prime numbers from the original array.

This code efficiently finds and displays all prime numbers within the generated array of random integers.

Q20. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly average.


In [ ]:
Ans. import numpy as np

# Assuming 30 days in the month
daily_temperatures = np.random.randint(15, 35, 30)

# Reshape the array into 4 weeks (assuming 7 days per week)
weekly_temperatures = daily_temperatures.reshape(4, 7)

# Calculate the average temperature for each week
weekly_averages = np.mean(weekly_temperatures, axis=1)

print("Daily Temperatures:", daily_temperatures)
print("Weekly Averages:", weekly_averages)

Explanation:

1.Generate Daily Temperatures:
* np.random.randint(15, 35, 30) creates an array of 30 random integers between 15 and 34 (inclusive) representing daily temperatures.
2. Reshape into Weekly Temperatures:
* daily_temperatures.reshape(4, 7) reshapes the 1D array into a 2D array with 4 rows (weeks) and 7 columns (days per week).
3. Calculate Weekly Averages:
* np.mean(weekly_temperatures, axis=1) calculates the mean (average) temperature along the first axis (rows), which represents each week.

This demonstrates how to use NumPy to efficiently calculate weekly average temperatures from daily temperature data.